http://localhost:3005/users/

###

POST http://localhost:3005/users HTTP/1.1
content-type: application/json

{
  "username": "bashiru11",
  "bio": "I am bashiru11",
  "age":11,
  "email":"bashiru1@gmail.com"
}

###

PUT http://localhost:3005/users/1 HTTP/1.1
content-type: application/json

{
  "username": "bashiru",
  "bio": "updated "
}

###

DELETE http://localhost:3005/users/2 HTTP/1.1
content-type: application/json
{
  "username": "bashiru",
  "bio": "updated "
}
###


get http://localhost:3005/users/one HTTP/1.1
content-type: application/json

{
  "email": "bashiru11@gmail.com"

}

###

get http://localhost:3005/users/email HTTP/1.1
content-type: application/json

