http://localhost:3005/users/

###

POST http://localhost:3005/users HTTP/1.1
content-type: application/json

{
  "username": "bashiru1",
  "bio": "I am a bashiru1",
  "age":10,
  "email":"bashiru@gmail.com"
}

###

PUT http://localhost:3005/users/1 HTTP/1.1
content-type: application/json

{
  "username": "bashiru",
  "bio": "updated "
}

###

DELETE http://localhost:3005/users/2 HTTP/1.1
content-type: application/json

###


get http://localhost:3005/users/2 HTTP/1.1
content-type: application/json